server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop
    username: ltldev
    password: 123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  #        format_sql: true
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
# url
api:
  prefix: api/v1

# environment variable, save token user
jwt:
  expiration: 2592000 #30 day, 30 * 24 * 60 * 60 = 2592000 s
  secretKey: "TaqlmGv1iEDMRiFp/pHuID1+T84IABfuA0xXh4GhiUI="